### ISSUE TITLE
Compatibility with 5.5.x

### ISSUE THREAD

**Issue by Roze** [laruence/taint#12]
Doesnt compile on 5.5.4.

/bin/sh /data/install/20130920/taint-1.2.2/libtool --mode=compile cc  -I. -I/data/install/20130920/taint-1.2.2 -DPHP_ATOM_INC -I/data/install/20130920/taint-1.2.2/include -I/data/install/20130920/taint-1.2.2/main -I/data/install/20130920/taint-1.2.2 -I/data/php554/include/php -I/data/php554/include/php/main -I/data/php554/include/php/TSRM -I/data/php554/include/php/Zend -I/data/php554/include/php/ext -I/data/php554/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /data/install/20130920/taint-1.2.2/taint.c -o taint.lo
mkdir .libs
 cc -I. -I/data/install/20130920/taint-1.2.2 -DPHP_ATOM_INC -I/data/install/20130920/taint-1.2.2/include -I/data/install/20130920/taint-1.2.2/main -I/data/install/20130920/taint-1.2.2 -I/data/php554/include/php -I/data/php554/include/php/main -I/data/php554/include/php/TSRM -I/data/php554/include/php/Zend -I/data/php554/include/php/ext -I/data/php554/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /data/install/20130920/taint-1.2.2/taint.c  -fPIC -DPIC -o .libs/taint.o
/data/install/20130920/taint-1.2.2/taint.c: In function ‘php_taint_get_zval_ptr_cv’:
/data/install/20130920/taint-1.2.2/taint.c:388:17: error: ‘struct _zend_execute_data’ has no member named ‘CVs’
/data/install/20130920/taint-1.2.2/taint.c: In function ‘php_taint_get_zval_ptr_ptr_cv’:
/data/install/20130920/taint-1.2.2/taint.c:417:17: error: ‘struct _zend_execute_data’ has no member named ‘CVs’
/data/install/20130920/taint-1.2.2/taint.c:437:46: error: ‘struct _zend_execute_data’ has no member named ‘CVs’
/data/install/20130920/taint-1.2.2/taint.c: In function ‘php_taint_echo_handler’:
/data/install/20130920/taint-1.2.2/taint.c:504:77: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:507:10: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:510:16: error: ‘struct _zend_execute_data’ has no member named ‘CVs’
/data/install/20130920/taint-1.2.2/taint.c: In function ‘php_taint_include_or_eval_handler’:
/data/install/20130920/taint-1.2.2/taint.c:541:77: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:544:10: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:547:16: error: ‘struct _zend_execute_data’ has no member named ‘CVs’
/data/install/20130920/taint-1.2.2/taint.c: In function ‘php_taint_concat_handler’:
/data/install/20130920/taint-1.2.2/taint.c:595:12: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:598:77: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:601:77: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:613:77: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:616:77: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c: In function ‘php_taint_binary_assign_op_obj_helper’:
/data/install/20130920/taint-1.2.2/taint.c:980:91: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:982:19: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:986:88: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1009:82: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1012:82: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1028:2: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1066:4: warning: passing argument 3 of ‘object->value.obj.handlers->get_property_ptr_ptr’ makes integer from pointer without a cast [enabled by default]
/data/install/20130920/taint-1.2.2/taint.c:1066:4: note: expected ‘int’ but argument is of type ‘struct zend_literal *’
/data/install/20130920/taint-1.2.2/taint.c:1066:4: error: too few arguments to function ‘object->value.obj.handlers->get_property_ptr_ptr’
/data/install/20130920/taint-1.2.2/taint.c: In function ‘php_taint_binary_assign_op_helper’:
/data/install/20130920/taint-1.2.2/taint.c:1196:90: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1228:80: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1231:80: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1256:40: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1257:88: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1258:79: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1267:80: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1270:80: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1288:86: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1315:4: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1316:4: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1317:4: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1317:4: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1317:4: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1317:4: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1317:4: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1317:4: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1375:3: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1377:3: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1377:3: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1377:3: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1377:3: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1377:3: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1377:3: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c: In function ‘php_taint_add_string_handler’:
/data/install/20130920/taint-1.2.2/taint.c:1416:12: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1430:77: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1433:77: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c: In function ‘php_taint_add_char_handler’:
/data/install/20130920/taint-1.2.2/taint.c:1473:12: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1487:77: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1490:77: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c: In function ‘php_taint_add_var_handler’:
/data/install/20130920/taint-1.2.2/taint.c:1532:12: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1546:77: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1549:77: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1564:77: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1567:77: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c: In function ‘php_taint_do_fcall_by_name_handler’:
/data/install/20130920/taint-1.2.2/taint.c:1896:40: error: ‘zend_execute_data’ has no member named ‘fbc’
/data/install/20130920/taint-1.2.2/taint.c:1897:37: error: ‘zend_execute_data’ has no member named ‘fbc’
/data/install/20130920/taint-1.2.2/taint.c:1910:66: error: ‘zend_execute_data’ has no member named ‘fbc’
/data/install/20130920/taint-1.2.2/taint.c: In function ‘php_taint_assign_handler’:
/data/install/20130920/taint-1.2.2/taint.c:1928:10: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1932:16: error: ‘struct _zend_execute_data’ has no member named ‘CVs’
/data/install/20130920/taint-1.2.2/taint.c:1954:10: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:1958:16: error: ‘struct _zend_execute_data’ has no member named ‘CVs’
/data/install/20130920/taint-1.2.2/taint.c: In function ‘php_taint_assign_ref_handler’:
/data/install/20130920/taint-1.2.2/taint.c:2005:10: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:2009:16: error: ‘struct _zend_execute_data’ has no member named ‘CVs’
/data/install/20130920/taint-1.2.2/taint.c:2029:10: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:2033:16: error: ‘struct _zend_execute_data’ has no member named ‘CVs’
/data/install/20130920/taint-1.2.2/taint.c: In function ‘php_taint_send_ref_handler’:
/data/install/20130920/taint-1.2.2/taint.c:2068:8: error: ‘zend_execute_data’ has no member named ‘fbc’
/data/install/20130920/taint-1.2.2/taint.c:2068:8: error: ‘zend_execute_data’ has no member named ‘fbc’
/data/install/20130920/taint-1.2.2/taint.c:2068:8: error: ‘zend_execute_data’ has no member named ‘fbc’
/data/install/20130920/taint-1.2.2/taint.c:2068:8: error: ‘zend_execute_data’ has no member named ‘fbc’
/data/install/20130920/taint-1.2.2/taint.c:2068:8: error: ‘zend_execute_data’ has no member named ‘fbc’
/data/install/20130920/taint-1.2.2/taint.c:2074:10: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:2078:16: error: ‘struct _zend_execute_data’ has no member named ‘CVs’
/data/install/20130920/taint-1.2.2/taint.c: In function ‘php_taint_send_var_handler’:
/data/install/20130920/taint-1.2.2/taint.c:2121:7: error: ‘zend_execute_data’ has no member named ‘fbc’
/data/install/20130920/taint-1.2.2/taint.c:2121:7: error: ‘zend_execute_data’ has no member named ‘fbc’
/data/install/20130920/taint-1.2.2/taint.c:2121:7: error: ‘zend_execute_data’ has no member named ‘fbc’
/data/install/20130920/taint-1.2.2/taint.c:2121:7: error: ‘zend_execute_data’ has no member named ‘fbc’
/data/install/20130920/taint-1.2.2/taint.c:2121:7: error: ‘zend_execute_data’ has no member named ‘fbc’
/data/install/20130920/taint-1.2.2/taint.c:2127:10: error: ‘zend_execute_data’ has no member named ‘Ts’
/data/install/20130920/taint-1.2.2/taint.c:2131:16: error: ‘struct _zend_execute_data’ has no member named ‘CVs’
/data/install/20130920/taint-1.2.2/taint.c: In function ‘zif_taint_strval’:
/data/install/20130920/taint-1.2.2/taint.c:2248:2: warning: ‘zend_get_parameters_ex’ is deprecated (declared at /data/php554/include/php/Zend/zend_API.h:238) [-Wdeprecated-declarations]
make: *** [taint.lo] Error 1

**Comment by sunchuo** [comment]
+1 on php 5.6.4

**Comment by silenceper** [comment]
+1 on php php-5.5.18

**Comment by briedis** [comment]
Voting for this :+1:

**Comment by sLIDe5** [comment]
Voting for this too :+1:

**Comment by starsea** [comment]
Voting for this too :+1:

**Comment by shaukei** [comment]
Voting for this again +1

**Comment by wakerman** [comment]
Voting for this again +1

**Comment by mickeyouyou** [comment]
Voting for this too :+1:

**Comment by cyangbo** [comment]
Voting for this again +1

**Comment by kid54001** [comment]
Voting for this too :+1:

**Comment by zhangran** [comment]
//@Laruence: 太忙了, 没精力搞啊, 现在只是打算等PHP7出来搞个PHP7的版本....//@orroz: 说明鸟哥的taint扩展很受欢迎啊！你就从了大家吧！[偷乐] //@Laruence: 这是逼我啊...[泪] http://t.cn/RA7o25c via http://www.weibo.com/1170999921/C9u5FbmMU?type=comment

**Comment by zhangran** [comment]
TRANSLATE-> :) //@Laruence: tài máng le , méi jīng lì gǎo ā , xiàn zài zhī shì dǎ suàn děng PHP7chū lái gǎo gè PHP7de bǎn běn ....//@orroz: shuō míng niǎo gē de taintkuò zhǎn hěn shòu huān yíng ā ！nǐ jiù cóng le dà jiā ba ！[tōu lè ] //@Laruence: zhè shì bī wǒ ā ...[lèi ] http://t.cn/RA7o25c via http://www.weibo.com/1170999921/C9u5FbmMU?type=comment

**Comment by silenceper** [comment]
期待鸟哥  的版本。 正好学习下

**Comment by staabm** [comment]
@laruence any plans for 5.5/5.6?

**Comment by laruence** [comment]
5.5 should already be supported

**Comment by staabm** [comment]
per latest pecl release it supports at max. 5.4.99

see https://pecl.php.net/package/taint/1.2.2

**Comment by staabm** [comment]
@laruence any news about taint and pecl on php55?

**Comment by netroby** [comment]
pecl install taint
pecl/taint requires PHP (version >= 5.2.0, version <= 5.4.99), installed version is 5.6.11

can not using taint with PHP 5.6

**Comment by laruence** [comment]
to all:   since taint is a complicated php extension, I am not going to support 5.6.  instead, I will keep maintaining php7.  which should work well now. (thanks to new string flag in php7, the implementation become much clean and simpler) thanks
