### PR TITLE
fix build with PHP 7.0

### PR DESCRIPTION
**Pull request by remicollet**
Without this patch
```

BUILDSTDERR: /builddir/build/BUILD/php70-php-pecl-taint-2.0.5/NTS/taint.c: In function 'php_taint_fetch_dimension_address':
BUILDSTDERR: /builddir/build/BUILD/php70-php-pecl-taint-2.0.5/NTS/taint.c:292:5: warning: implicit declaration of function 'ZVAL_ERROR'; did you mean 'DL_ERROR'? [-Wimplicit-functi
on-declaration]
BUILDSTDERR:      ZVAL_ERROR(result);
BUILDSTDERR:      ^~~~~~~~~~
BUILDSTDERR:      DL_ERROR

```

And trying to load the extension:
`PHP Warning:  PHP Startup: Unable to load dynamic library .../modules/taint.so: undefined symbol: ZVAL_ERROR in Unknown on line 0`

I notice the compat macro `TAINT_ERR_ZVAL`, but doesn't seem usable

### CODE REVIEW

**Comment by remicollet** [comment]
Sadly not in 2.0.6, so PHP 7.0 build is still broken

**Comment by laruence** [comment]
all 7.0.x? or only 7.0.0?

**Comment by remicollet** [comment]
All php < 7.1 ;)
(tested with latest 7.0.33)

**Comment by laruence** [comment]
it should be fixed...
